name: Ludo Bouan
favicon: null
layout_spectrum: 0.75046
typography_spectrum: 0.8877459461800754
title: Ludo Bouan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b49484'
    - '#5a6d84'
    - '#021328'
    - '#493f48'
    - '#fedead'
  brandStrength: 0.7178720452357084
  lightness: 0.7944799729157239
  saturation: 0.7216906943358481
  rhythmicContrast: 0.47444745479151607
purpose: []
